liferay-instance-settings-d5f7j8:
  name: Master Liferay Instance Settings Fragment Service
  pid: com.liferay.fragment.configuration.FragmentServiceConfiguration
  propagateChanges: true
  propagateContributedFragmentChanges: true
  type: instanceSettings